# Generated by Django 6.0.4 on 2026-05-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('result_highlight', models.CharField(help_text="e.g. '3x revenue increase'", max_length=300)),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies', max_length=500)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Font Awesome icon class, e.g. 'fas fa-code'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('problem', models.TextField(blank=True, help_text='Problem statement for detail view')),
                ('solution', models.TextField(blank=True, help_text='Solution description for detail view')),
                ('benefits', models.TextField(blank=True, help_text='Key benefits, one per line')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='We Build Scalable Digital Products', max_length=300)),
                ('hero_subheading', models.TextField(default='Transforming ideas into high-performance digital experiences that drive growth.')),
                ('about_intro', models.TextField(default='We are a team of passionate developers and designers.')),
                ('about_mission', models.TextField(default='To deliver world-class digital solutions.')),
                ('about_vision', models.TextField(default='To be the most trusted digital partner globally.')),
                ('stat_projects', models.CharField(default='50+', max_length=50)),
                ('stat_experience', models.CharField(default='3+', max_length=50)),
                ('stat_clients', models.CharField(default='40+', max_length=50)),
                ('contact_email', models.EmailField(default='hello@mzify.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+880 1234 567890', max_length=20)),
                ('whatsapp_number', models.CharField(default='8801234567890', help_text='WhatsApp number without + sign', max_length=20)),
                ('footer_text', models.CharField(default='© 2026 mzify. All rights reserved.', max_length=300)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(help_text="e.g. 'CEO, TechCorp'", max_length=200)),
                ('feedback', models.TextField()),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
