# Generated by Django 6.0.4 on 2026-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service card image (optional)', null=True, upload_to='services/'),
        ),
    ]
