# Generated by Django 5.2.8 on 2026-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0003_category_clientlogo_teammember_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.CharField(default='fas fa-newspaper', help_text='Font Awesome icon for the post', max_length=100),
        ),
    ]
