# Generated by Django 5.2.8 on 2026-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0004_post_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_thumbnail',
            field=models.URLField(blank=True, help_text='Link to external image (e.g. Unsplash)'),
        ),
    ]
