# Generated by Django 5.2.8 on 2026-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0009_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(help_text="Fallback text if price_usd is 0, e.g. 'Custom'", max_length=100),
        ),
    ]
