# Generated by Django 6.0.5 on 2026-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0010_package_price_usd_alter_package_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_bn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name_bn',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name_en',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='result_highlight_bn',
            field=models.CharField(help_text="e.g. '3x revenue increase'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='result_highlight_en',
            field=models.CharField(help_text="e.g. '3x revenue increase'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits_bn',
            field=models.TextField(blank=True, help_text='Key benefits, one per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits_en',
            field=models.TextField(blank=True, help_text='Key benefits, one per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='problem_bn',
            field=models.TextField(blank=True, help_text='Problem statement for detail view', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='problem_en',
            field=models.TextField(blank=True, help_text='Problem statement for detail view', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='solution_bn',
            field=models.TextField(blank=True, help_text='Solution description for detail view', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='solution_en',
            field=models.TextField(blank=True, help_text='Solution description for detail view', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_intro_bn',
            field=models.TextField(default='We are a team of passionate developers and designers.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_intro_en',
            field=models.TextField(default='We are a team of passionate developers and designers.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_mission_bn',
            field=models.TextField(default='To deliver world-class digital solutions.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_mission_en',
            field=models.TextField(default='To deliver world-class digital solutions.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_vision_bn',
            field=models.TextField(default='To be the most trusted digital partner globally.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_vision_en',
            field=models.TextField(default='To be the most trusted digital partner globally.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_bn',
            field=models.CharField(default='© 2026 DevSquad. All rights reserved.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_en',
            field=models.CharField(default='© 2026 DevSquad. All rights reserved.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_headline_bn',
            field=models.CharField(default='We Build Scalable Digital Products', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_headline_en',
            field=models.CharField(default='We Build Scalable Digital Products', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subheading_bn',
            field=models.TextField(default='Transforming ideas into high-performance digital experiences that drive growth.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subheading_en',
            field=models.TextField(default='Transforming ideas into high-performance digital experiences that drive growth.', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(help_text="e.g. '$2,500' or 'Custom'", max_length=100),
        ),
    ]
