# Generated by Django 5.2.8 on 2026-05-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsqaud', '0012_remove_faq_answer_bn_remove_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='github',
        ),
    ]
